import type { ReactElement } from 'react'
import Head from 'next/head'
import Navigation from './navigation/Navigation'
import Footer from './footer/Footer'

const Layout = ({ children, title }: any) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='stylesheet' href='https://rsms.me/inter/inter.css'></link>
      </Head>
      <header>
        <Navigation />
      </header>
      <main>{children}</main>
      <footer>
        <Footer />
      </footer>
    </>
  )
}

export default Layout
